[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'ffmpeg', 'deno']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'python app.py'
