[phases.setup]
nixPkgs = ['python311', 'ffmpeg', 'deno']

[phases.install]
cmds = [
    'python -m ensurepip --upgrade || curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py',
    'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'python app.py'
